name: CD for Next.js App

on:
  pull_request:
    branches:
      - deploy  # 當 PR 發送到 deploy 分支時觸發

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 檢出代碼
    - name: Checkout code
      uses: actions/checkout@v3

    # 登錄 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_YC }}
        password: ${{ secrets.DOCKER_PASSWORD_YC }}

    # 構建 Docker 映像
    - name: Build Docker image
      run: |
        docker build --platform=linux/amd64 -t ychaocode/nextjs-app:${{ github.sha }} ./cafemate_app

    # 推送 Docker 映像至 Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ychaocode/nextjs-app:${{ github.sha }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # 使用 SSH 登入 EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker pull ychaocode/nextjs-app:${{ github.sha }}
          docker stop nextjs-app || true
          docker rm nextjs-app || true
          docker run -d --name nextjs-app -p 3000:3000 ychaocode/nextjs-app:${{ github.sha }}
